spring:
  application:
    name: transactional-event-listener
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
#    url: jdbc:h2:file:./data/sample
#    schema: classpath:db/schema.sql
    username: root
    password: root
